### One Hot Encoding

In [1]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np
# Sample categorical data
data = np.array([['Red'], ['Green'], ['Blue'], ['Red'], ['Blue']])
encoder = OneHotEncoder(sparse_output=False)
encoded_data = encoder.fit_transform(data)

In [2]:
encoded_data

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

# Bag of Words (BoW) Example

In [3]:
import pandas as pd

In [4]:
df = pd.DataFrame({
    "text":["people watch dswithbappy",
                         "dswithbappy watch dswithbappy",
                         "people write comment",
                          "dswithbappy write comment"],"output":[1,1,0,0]
})

In [5]:
df

                            text  output
0       people watch dswithbappy       1
1  dswithbappy watch dswithbappy       1
2           people write comment       0
3      dswithbappy write comment       0

In [6]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
bow = cv.fit_transform(df['text'])

In [7]:
bow

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 11 stored elements and shape (4, 5)>

In [8]:
bow.toarray()

array([[0, 1, 1, 1, 0],
       [0, 2, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [1, 1, 0, 0, 1]])

In [9]:
#vocabulary
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'dswithbappy': 1, 'write': 4, 'comment': 0}

In [10]:
# Show feature names (the actual words in the vocabulary)
print("\nFeature Names (columns):")
print(cv.get_feature_names_out())

Feature Names (columns):
['comment' 'dswithbappy' 'people' 'watch' 'write']

# N grams

In [11]:
df = pd.DataFrame({"text":["people watch dswithbappy",
                         "dswithbappy watch dswithbappy",
                         "people write comment",
                          "dswithbappy write comment"],"output":[1,1,0,0]})
df

                            text  output
0       people watch dswithbappy       1
1  dswithbappy watch dswithbappy       1
2           people write comment       0
3      dswithbappy write comment       0

In [12]:
# BI grams
cv = CountVectorizer(ngram_range=(2, 2))

In [13]:
bow = cv.fit_transform(df['text'])

In [14]:
bow.toarray()

array([[0, 0, 1, 0, 1, 0],
       [1, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 1],
       [0, 1, 0, 0, 0, 1]])

In [15]:
#vocabulary
print(cv.vocabulary_)

{'people watch': 2, 'watch dswithbappy': 4, 'dswithbappy watch': 0, 'people write': 3, 'write comment': 5, 'dswithbappy write': 1}

In [16]:
#Tri grams
cv = CountVectorizer(ngram_range=(3, 3))
bow = cv.fit_transform(df['text'])

In [17]:
bow.toarray()

array([[0, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 1, 0, 0]])

In [18]:
print(cv.vocabulary_)

{'people watch dswithbappy': 2, 'dswithbappy watch dswithbappy': 0, 'people write comment': 3, 'dswithbappy write comment': 1}

# TF-IDF (Term frequency- Inverse document frequency

In [19]:
f = pd.DataFrame({"text":["people watch dswithbappy",
                         "dswithbappy watch dswithbappy",
                         "people write comment",
                          "dswithbappy write comment"],"output":[1,1,0,0]})

df

                            text  output
0       people watch dswithbappy       1
1  dswithbappy watch dswithbappy       1
2           people write comment       0
3      dswithbappy write comment       0

In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer()

In [21]:
arr = tfidf_vectorizer.fit_transform(df['text']).toarray()

In [22]:
arr

array([[0.        , 0.49681612, 0.61366674, 0.61366674, 0.        ],
       [0.        , 0.8508161 , 0.        , 0.52546357, 0.        ],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.57735027],
       [0.61366674, 0.49681612, 0.        , 0.        , 0.61366674]])

# Word2vec 
### is a popular word embedding technique that represents words as dense vectors in a continuous vector space. It captures semantic relationships between words based on their co-occurrence in a large corpus of text. The two main architectures for Word2vec are Continuous Bag of Words (CBOW) and Skip-gram. CBOW predicts a target word based on its context, while Skip-gram predicts the context given a target word. Word2vec is widely used in natural language processing tasks to capture the meaning and relationships between words.

In [23]:
import pandas as pd 
import numpy as np
import gensim
import os

In [24]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /Users/al-amen/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /Users/al-
[nltk_data]     amen/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [25]:
story = []
for filename in os.listdir('../Day-4'):
    if filename.endswith('.ipynb'):
        pass
    f = open(os.path.join('../Day-4', filename))
    corpus = f.read()
    raw_sent = sent_tokenize(corpus)
    for sent in raw_sent:
        story.append(simple_preprocess(sent))

In [26]:
story

[['cells',
  'cell_type',
  'markdown',
  'id',
  'metadata',
  'source',
  'one',
  'hot',
  'encoding',
  'cell_type',
  'code',
  'execution_count',
  'id',
  'cd',
  'metadata',
  'outputs',
  'source',
  'from',
  'sklearn',
  'preprocessing',
  'import',
  'onehotencoder',
  'import',
  'numpy',
  'as',
  'np',
  'sample',
  'categorical',
  'data',
  'data',
  'np',
  'array',
  'red',
  'green',
  'blue',
  'red',
  'blue',
  'encoder',
  'onehotencoder',
  'sparse_output',
  'false',
  'encoded_data',
  'encoder',
  'fit_transform',
  'data',
  'cell_type',
  'code',
  'execution_count',
  'id',
  'ba',
  'metadata',
  'outputs',
  'data',
  'text',
  'plain',
  'array'],
 [],
 [],
 [],
 [],
 ['execution_count',
  'metadata',
  'output_type',
  'execute_result',
  'source',
  'encoded_data',
  'cell_type',
  'markdown',
  'id',
  'metadata',
  'source',
  'bag',
  'of',
  'words',
  'bow',
  'example',
  'cell_type',
  'code',
  'execution_count',
  'id',
  'metadata',
  'outputs',
  'source',
  'import',
  'pandas',
  'as',
  'pd',
  'cell_type',
  'code',
  'execution_count',
  'id',
  'metadata',
  'outputs',
  'source',
  'df',
  'pd',
  'dataframe',
  'text',
  'people',
  'watch',
  'dswithbappy',
  'dswithbappy',
  'watch',
  'dswithbappy',
  'people',
  'write',
  'comment',
  'dswithbappy',
  'write',
  'comment',
  'output',
  'cell_type',
  'code',
  'execution_count',
  'id',
  'bf',
  'metadata',
  'outputs',
  'data',
  'text',
  'html',
  'div',
  'style',
  'scoped',
  'dataframe',
  'tbody',
  'tr',
  'th',
  'only',
  'of',
  'type',
  'vertical',
  'align',
  'middle',
  'dataframe',
  'tbody',
  'tr',
  'th',
  'vertical',
  'align',
  'top',
  'dataframe',
  'thead',
  'th',
  'text',
  'align',
  'right',
  'style',
  'table',
  'border',
  'class',
  'dataframe',
  'thead',
  'tr',
  'style',
  'text',
  'align',
  'right',
  'th',
  'th',
  'th',
  'text',
  'th',
  'th',
  'output',
  'th',
  'tr',
  'thead',
  'tbody',
  'tr',
  'th',
  'th',
  'td',
  'people',
  'watch',
  'dswithbappy',
  'td',
  'td',
  'td',
  'tr',
  'tr',
  'th',
  'th',
  'td',
  'dswithbappy',
  'watch',
  'dswithbappy',
  'td',
  'td',
  'td',
  'tr',
  'tr',
  'th',
  'th',
  'td',
  'people',
  'write',
  'comment',
  'td',
  'td',
  'td',
  'tr',
  'tr',
  'th',
  'th',
  'td',
  'dswithbappy',
  'write',
  'comment',
  'td',
  'td',
  'td',
  'tr',
  'tbody',
  'table',
  'div',
  'text',
  'plain',
  'text',
  'output',
  'people',
  'watch',
  'dswithbappy',
  'dswithbappy',
  'watch',
  'dswithbappy',
  'people',
  'write',
  'comment',
  'dswithbappy',
  'write',
  'comment',
  'execution_count',
  'metadata',
  'output_type',
  'execute_result',
  'source',
  'df',
  'cell_type',
  'code',
  'execution_count',
  'id',
  'eed',
  'metadata',
  'outputs',
  'source',
  'from',
  'sklearn',
  'text',
  'import',
  'countvectorizer',
  'cv',
  'countvectorizer',
  'bow',
  'cv',
  'fit_transform',
  'df',
  'text',
  'cell_type',
  'code',
  'execution_count',
  'id',
  'metadata',
  'outputs',
  'data',
  'text',
  'plain',
  'compressed',
  'sparse',
  'row',
  'sparse',
  'matrix',
  'of',
  'dtype',
  'int',
  'twith',
  'stored',
  'elements',
  'and',
  'shape',
  'execution_count',
  'metadata',
  'output_type',
  'execute_result',
  'source',
  'bow',
  'cell_type',
  'code',
  'execution_count',
  'id',
  'bf',
  'metadata',
  'outputs',
  'data',
  'text',
  'plain',
  'array',
  'execution_count',
  'metadata',
  'output_type',
  'execute_result',
  'source',
  'bow',
  'toarray',
  'cell_type',
  'code',
  'execution_count',
  'id',
  'metadata',
  'outputs',
  'name',
  'stdout',
  'output_type',
  'stream',
  'text',
  'people',
  'watch',
  'dswithbappy',
  'write',
  'comment',
  'source',
  'vocabulary',
  'print',
  'cv',
  'vocabulary_',
  'cell_type',
  'code',
  'execution_count',
  'id',
  'dd',
  'metadata',
  'outputs',
  'name',
  'stdout',
  'output_type',
  'stream',
  'text',
  'feature',
  'names',
  'columns',
  'comment',
  'dswithbappy',
  'people',
  'watch',
  'write',
  'source',
  'show',
  'feature',
  'names',
  'the',
  'actual',
  'words',
  'in',
  'the',
  'vocabulary',
  'print',
  'nfeature',
  'names',
  'columns',
  'print',
  'cv',
  'cell_type',
  'markdown',
  'id',
  'acfa',
  'metadata',
  'source',
  'grams',
  'cell_type',
  'code',
  'execution_count',
  'id',
  'fcec',
  'metadata',
  'outputs',
  'data',
  'text',
  'html',
  'div',
  'style',
  'scoped',
  'dataframe',
  'tbody',
  'tr',
  'th',
  'only',
  'of',
  'type',
  'vertical',
  'align',
  'middle',
  'dataframe',
  'tbody',
  'tr',
  'th',
  'vertical',
  'align',
  'top',
  'dataframe',
  'thead',
  'th',
  'text',
  'align',
  'right',
  'style',
  'table',
  'border',
  'class',
  'dataframe',
  'thead',
  'tr',
  'style',
  'text',
  'align',
  'right',
  'th',
  'th',
  'th',
  'text',
  'th',
  'th',
  'output',
  'th',
  'tr',
  'thead',
  'tbody',
  'tr',
  'th',
  'th',
  'td',
  'people',
  'watch',
  'dswithbappy',
  'td',
  'td',
  'td',
  'tr',
  'tr',
  'th',
  'th',
  'td',
  'dswithbappy',
  'watch',
  'dswithbappy',
  'td',
  'td',
  'td',
  'tr',
  'tr',
  'th',
  'th',
  'td',
  'people',
  'write',
  'comment',
  'td',
  'td',
  'td',
  'tr',
  'tr',
  'th',
  'th',
  'td',
  'dswithbappy',
  'write',
  'comment',
  'td',
  'td',
  'td',
  'tr',
  'tbody',
  'table',
  'div',
  'text',
  'plain',
  'text',
  'output',
  'people',
  'watch',
  'dswithbappy',
  'dswithbappy',
  'watch',
  'dswithbappy',
  'people',
  'write',
  'comment',
  'dswithbappy',
  'write',
  'comment',
  'execution_count',
  'metadata',
  'output_type',
  'execute_result',
  'source',
  'df',
  'pd',
  'dataframe',
  'text',
  'people',
  'watch',
  'dswithbappy',
  'dswithbappy',
  'watch',
  'dswithbappy',
  'people',
  'write',
  'comment',
  'dswithbappy',
  'write',
  'comment',
  'output',
  'df',
  'cell_type',
  'code',
  'execution_count',
  'id',
  'ea',
  'dbd',
  'metadata',
  'outputs',
  'source',
  'bi',
  'grams',
  'cv',
  'countvectorizer',
  'ngram_range',
  'cell_type',
  'code',
  'execution_count',
  'id',
  'metadata',
  'outputs',
  'source',
  'bow',
  'cv',
  'fit_transform',
  'df',
  'text',
  'cell_type',
  'code',
  'execution_count',
  'id',
  'edb',
  'metadata',
  'outputs',
  'data',
  'text',
  'plain',
  'array',
  'execution_count',
  'metadata',
  'output_type',
  'execute_result',
  'source',
  'bow',
  'toarray',
  'cell_type',
  'code',
  'execution_count',
  'id',
  'metadata',
  'outputs',
  'name',
  'stdout',
  'output_type',
  'stream',
  'text',
  'people',
  'watch',
  'watch',
  'dswithbappy',
  'dswithbappy',
  'watch',
  'people',
  'write',
  'write',
  'comment',
  'dswithbappy',
  'write',
  'source',
  'vocabulary',
  'print',
  'cv',
  'vocabulary_',
  'cell_type',
  'code',
  'execution_count',
  'id',
  'fa',
  'metadata',
  'outputs',
  'source',
  'tri',
  'grams',
  'cv',
  'countvectorizer',
  'ngram_range',
  'bow',
  'cv',
  'fit_transform',
  'df',
  'text',
  'cell_type',
  'code',
  'execution_count',
  'id',
  'metadata',
  'outputs',
  'data',
  'text',
  'plain',
  'array',
  'execution_count',
  'metadata',
  'output_type',
  'execute_result',
  'source',
  'bow',
  'toarray',
  'cell_type',
  'code',
  'execution_count',
  'id',
  'dbda',
  'metadata',
  'outputs',
  'name',
  'stdout',
  'output_type',
  'stream',
  'text',
  'people',
  'watch',
  'dswithbappy',
  'dswithbappy',
  'watch',
  'dswithbappy',
  'people',
  'write',
  'comment',
  'dswithbappy',
  'write',
  'comment',
  'source',
  'print',
  'cv',
  'vocabulary_',
  'cell_type',
  'markdown',
  'id',
  'metadata',
  'source',
  'tf',
  'idf',
  'term',
  'frequency',
  'inverse',
  'document',
  'frequency',
  'cell_type',
  'code',
  'execution_count',
  'id',
  'metadata',
  'outputs',
  'data',
  'text',
  'html',
  'div',
  'style',
  'scoped',
  'dataframe',
  'tbody',
  'tr',
  'th',
  'only',
  'of',
  'type',
  'vertical',
  'align',
  'middle',
  'dataframe',
  'tbody',
  'tr',
  'th',
  'vertical',
  'align',
  'top',
  'dataframe',
  'thead',
  'th',
  'text',
  'align',
  'right',
  'style',
  'table',
  'border',
  'class',
  'dataframe',
  'thead',
  'tr',
  'style',
  'text',
  'align',
  'right',
  'th',
  'th',
  'th',
  'text',
  'th',
  'th',
  'output',
  'th',
  'tr',
  'thead',
  'tbody',
  'tr',
  'th',
  'th',
  'td',
  'people',
  'watch',
  'dswithbappy',
  'td',
  'td',
  'td',
  'tr',
  'tr',
  'th',
  'th',
  'td',
  'dswithbappy',
  'watch',
  'dswithbappy',
  'td',
  'td',
  'td',
  'tr',
  'tr',
  'th',
  'th',
  'td',
  'people',
  'write',
  'comment',
  'td',
  'td',
  'td',
  'tr',
  'tr',
  'th',
  'th',
  'td',
  'dswithbappy',
  'write',
  'comment',
  'td',
  'td',
  'td',
  'tr',
  'tbody',
  'table',
  'div',
  'text',
  'plain',
  'text',
  'output',
  'people',
  'watch',
  'dswithbappy',
  'dswithbappy',
  'watch',
  'dswithbappy',
  'people',
  'write',
  'comment',
  'dswithbappy',
  'write',
  'comment',
  'execution_count',
  'metadata',
  'output_type',
  'execute_result',
  'source',
  'pd',
  'dataframe',
  'text',
  'people',
  'watch',
  'dswithbappy',
  'dswithbappy',
  'watch',
  'dswithbappy',
  'people',
  'write',
  'comment',
  'dswithbappy',
  'write',
  'comment',
  'output',
  'df',
  'cell_type',
  'code',
  'execution_count',
  'id',
  'metadata',
  'outputs',
  'source',
  'from',
  'sklearn',
  'text',
  'import',
  'tfidfvectorizer',
  'tfidfvectorizer',
  'cell_type',
  'code',
  'execution_count',
  'id',
  'metadata',
  'outputs',
  'source',
  'arr',
  'fit_transform',
  'df',
  'text',
  'toarray',
  'cell_type',
  'code',
  'execution_count',
  'id',
  'metadata',
  'outputs',
  'data',
  'text',
  'plain',
  'array'],
 [],
 ['execution_count',
  'metadata',
  'output_type',
  'execute_result',
  'source',
  'arr',
  'cell_type',
  'markdown',
  'id',
  'ae',
  'metadata',
  'source',
  'word',
  'vec',
  'is',
  'popular',
  'word',
  'embedding',
  'technique',
  'that',
  'represents',
  'words',
  'as',
  'dense',
  'vectors',
  'in',
  'continuous',
  'vector',
  'space'],
 ['it',
  'captures',
  'semantic',
  'relationships',
  'between',
  'words',
  'based',
  'on',
  'their',
  'co',
  'occurrence',
  'in',
  'large',
  'corpus',
  'of',
  'text'],
 ['the',
  'two',
  'main',
  'architectures',
  'for',
  'word',
  'vec',
  'are',
  'continuous',
  'bag',
  'of',
  'words',
  'cbow',
  'and',
  'skip',
  'gram'],
 ['cbow',
  'predicts',
  'target',
  'word',
  'based',
  'on',
  'its',
  'context',
  'while',
  'skip',
  'gram',
  'predicts',
  'the',
  'context',
  'given',
  'target',
  'word'],
 ['word',
  'vec',
  'is',
  'widely',
  'used',
  'in',
  'natural',
  'language',
  'processing',
  'tasks',
  'to',
  'capture',
  'the',
  'meaning',
  'and',
  'relationships',
  'between',
  'words'],
 ['cell_type',
  'code',
  'execution_count',
  'id',
  'metadata',
  'outputs',
  'source',
  'import',
  'pandas',
  'as',
  'pd',
  'import',
  'numpy',
  'as',
  'np',
  'import',
  'gensim',
  'import',
  'os',
  'cell_type',
  'code',
  'execution_count',
  'null',
  'id',
  'ab',
  'metadata',
  'outputs',
  'source',
  'from',
  'nltk',
  'import',
  'sent_tokenize',
  'from',
  'gensim',
  'utils',
  'import',
  'import',
  'nltk',
  'nltk',
  'download',
  'punkt',
  'nltk',
  'download',
  'punkt_tab',
  'cell_type',
  'code',
  'execution_count',
  'null',
  'id',
  'fb',
  'metadata',
  'outputs',
  'source',
  'story',
  'for',
  'filename',
  'in',
  'os',
  'listdir',
  'day',
  'if',
  'filename',
  'endswith',
  'ipynb',
  'pass',
  'open',
  'os',
  'path',
  'join',
  'day',
  'filename',
  'corpus',
  'read',
  'raw_sent',
  'sent_tokenize',
  'corpus',
  'for',
  'sent',
  'in',
  'raw_sent',
  'story',
  'append',
  'sent',
  'cell_type',
  'code',
  'execution_count',
  'null',
  'id',
  'fa',
  'metadata',
  'outputs',
  'data',
  'text',
  'plain',
  'cells',
  'cell_type',
  'markdown',
  'id',
  'metadata',
  'source',
  'one',
  'hot',
  'encoding',
  'cell_type',
  'code',
  'execution_count',
  'id',
  'cd',
  'metadata',
  'outputs',
  'source',
  'from',
  'sklearn',
  'preprocessing',
  'import',
  'onehotencoder',
  'import',
  'numpy',
  'as',
  'np',
  'sample',
  'categorical',
  'data',
  'data',
  'np',
  'array',
  'red',
  'green',
  'blue',
  'red',
  'blue',
  'encoder',
  'onehotencoder',
  'sparse_output',
  'false',
  'encoded_data',
  'encoder',
  'fit_transform',
  'data',
  'cell_type',
  'code',
  'execution_count',
  'id',
  'ba',
  'metadata',
  'outputs',
  'data',
  'text',
  'plain',
  'array',
  'execution_count',
  'metadata',
  'output_type',
  'execute_result',
  'source',
  'encoded_data',
  'cell_type',
  'markdown',
  'id',
  'metadata',
  'source',
  'bag',
  'of',
  'words',
  'bow',
  'example',
  'cell_type',
  'code',
  'execution_count',
  'id',
  'metadata',
  'outputs',
  'source',
  'import',
  'pandas',
  'as',
  'pd',
  'cell_type',
  'code',
  'execution_count',
  'id',
  'metadata',
  'outputs',
  'source',
  'df',
  'pd',
  'dataframe',
  'text',
  'people',
  'watch',
  'dswithbappy',
  'dswithbappy',
  'watch',
  'dswithbappy',
  'people',
  'write',
  'comment',
  'dswithbappy',
  'write',
  'comment',
  'output',
  'cell_type',
  'code',
  'execution_count',
  'id',
  'bf',
  'metadata',
  'outputs',
  'data',
  'text',
  'html',
  'div',
  'style',
  'scoped',
  'dataframe',
  'tbody',
  'tr',
  'th',
  'only',
  'of',
  'type',
  'vertical',
  'align',
  'middle',
  'dataframe',
  'tbody',
  'tr',
  'th',
  'vertical',
  'align',
  'top',
  'dataframe',
  'thead',
  'th',
  'text',
  'align',
  'right',
  'style',
  'table',
  'border',
  'class',
  'dataframe',
  'thead',
  'tr',
  'style',
  'text',
  'align',
  'right',
  'th',
  'th',
  'th',
  'text',
  'th',
  'th',
  'output',
  'th',
  'tr',
  'thead',
  'tbody',
  'tr',
  'th',
  'th',
  'td',
  'people',
  'watch',
  'dswithbappy',
  'td',
  'td',
  'td',
  'tr',
  'tr',
  'th',
  'th',
  'td',
  'dswithbappy',
  'watch',
  'dswithbappy',
  'td',
  'td',
  'td',
  'tr',
  'tr',
  'th',
  'th',
  'td',
  'people',
  'write',
  'comment',
  'td',
  'td',
  'td',
  'tr',
  'tr',
  'th',
  'th',
  'td',
  'dswithbappy',
  'write',
  'comment',
  'td',
  'td',
  'td',
  'tr',
  'tbody',
  'table',
  'div',
  'text',
  'plain',
  'text',
  'output',
  'people',
  'watch',
  'dswithbappy',
  'dswithbappy',
  'watch',
  'dswithbappy',
  'people',
  'write',
  'comment',
  'dswithbappy',
  'write',
  'comment',
  'execution_count',
  'metadata',
  'output_type',
  'execute_result',
  'source',
  'df',
  'cell_type',
  'code',
  'execution_count',
  'id',
  'eed',
  'metadata',
  'outputs',
  'source',
  'from',
  'sklearn',
  'text',
  'import',
  'countvectorizer',
  'cv',
  'countvectorizer',
  'bow',
  'cv',
  'fit_transform',
  'df',
  'text',
  'cell_type',
  'code',
  'execution_count',
  'id',
  'metadata',
  'outputs',
  'data',
  'text',
  'plain',
  'compressed',
  'sparse',
  'row',
  'sparse',
  'matrix',
  'of',
  'dtype',
  'int',
  'twith',
  'stored',
  'elements',
  'and',
  'shape',
  'execution_count',
  'metadata',
  'output_type',
  'execute_result',
  'source',
  'bow',
  'cell_type',
  'code',
  'execution_count',
  'id',
  'bf',
  'metadata',
  'outputs',
  'data',
  'text',
  'plain',
  'array',
  'execution_count',
  'metadata',
  'output_type',
  'execute_result',
  'source',
  'bow',
  'toarray',
  'cell_type',
  'code',
  'execution_count',
  'id',
  'metadata',
  'outputs',
  'name',
  'stdout',
  'output_type',
  'stream',
  'text',
  'people',
  'watch',
  'dswithbappy',
  'write',
  'comment',
  'source',
  'vocabulary',
  'print',
  'cv',
  'vocabulary_',
  'cell_type',
  'code',
  'execution_count',
  'id',
  'dd',
  'metadata',
  'outputs',
  'name',
  'stdout',
  'output_type',
  'stream',
  'text',
  'feature',
  'names',
  'columns',
  'comment',
  'dswithbappy',
  'people',
  'watch',
  'write',
  'source',
  'show',
  'feature',
  'names',
  'the',
  'actual',
  'words',
  'in',
  'the',
  'vocabulary',
  'print',
  'nfeature',
  'names',
  'columns',
  'print',
  'cv',
  'cell_type',
  'markdown',
  'id',
  'acfa',
  'metadata',
  'source',
  'grams',
  'cell_type',
  'code',
  'execution_count',
  'id',
  'fcec',
  'metadata',
  'outputs',
  'data',
  'text',
  'html',
  'div',
  'style',
  'scoped',
  'dataframe',
  'tbody',
  'tr',
  'th',
  'only',
  'of',
  'type',
  'vertical',
  'align',
  'middle',
  'dataframe',
  'tbody',
  'tr',
  'th',
  'vertical',
  'align',
  'top',
  'dataframe',
  'thead',
  'th',
  'text',
  'align',
  'right',
  'style',
  'table',
  'border',
  'class',
  'dataframe',
  'thead',
  'tr',
  'style',
  'text',
  'align',
  'right',
  'th',
  'th',
  'th',
  'text',
  'th',
  'th',
  'output',
  'th',
  'tr',
  'thead',
  'tbody',
  'tr',
  'th',
  'th',
  'td',
  'people',
  'watch',
  'dswithbappy',
  'td',
  'td',
  'td',
  'tr',
  'tr',
  'th',
  'th',
  'td',
  'dswithbappy',
  'watch',
  'dswithbappy',
  'td',
  'td',
  'td',
  'tr',
  'tr',
  'th',
  'th',
  'td',
  'people',
  'write',
  'comment',
  'td',
  'td',
  'td',
  'tr',
  'tr',
  'th',
  'th',
  'td',
  'dswithbappy',
  'write',
  'comment',
  'td',
  'td',
  'td',
  'tr',
  'tbody',
  'table',
  'div',
  'text',
  'plain',
  'text',
  'output',
  'people',
  'watch',
  'dswithbappy',
  'dswithbappy',
  'watch',
  'dswithbappy',
  'people',
  'write',
  'comment',
  'dswithbappy',
  'write',
  'comment',
  'execution_count',
  'metadata',
  'output_type',
  'execute_result',
  'source',
  'df',
  'pd',
  'dataframe',
  'text',
  'people',
  'watch',
  'dswithbappy',
  'dswithbappy',
  'watch',
  'dswithbappy',
  'people',
  'write',
  'comment',
  'dswithbappy',
  'write',
  'comment',
  'output',
  'df',
  'cell_type',
  'code',
  'execution_count',
  'id',
  'ea',
  'dbd',
  'metadata',
  'outputs',
  'source',
  'bi',
  'grams',
  'cv',
  'countvectorizer',
  'ngram_range',
  'cell_type',
  'code',
  'execution_count',
  'id',
  'metadata',
  'outputs',
  'source',
  'bow',
  'cv',
  'fit_transform',
  'df',
  'text',
  'cell_type',
  'code',
  'execution_count',
  'id',
  'edb',
  'metadata',
  'outputs',
  'data',
  'text',
  'plain',
  'array',
  'execution_count',
  'metadata',
  'output_type',
  'execute_result',
  'source',
  'bow',
  'toarray',
  'cell_type',
  'code',
  'execution_count',
  'id',
  'metadata',
  'outputs',
  'name',
  'stdout',
  'output_type',
  'stream',
  'text',
  'people',
  'watch',
  'watch',
  'dswithbappy',
  'dswithbappy',
  'watch',
  'people',
  'write',
  'write',
  'comment',
  'dswithbappy',
  'write',
  'source',
  'vocabulary',
  'print',
  'cv',
  'vocabulary_',
  'cell_type',
  'code',
  'execution_count',
  'id',
  'fa',
  'metadata',
  'outputs',
  'source',
  'tri',
  'grams',
  'cv',
  'countvectorizer',
  'ngram_range',
  'bow',
  'cv',
  'fit_transform',
  'df',
  'text',
  'cell_type',
  'code',
  'execution_count',
  'id',
  'metadata',
  'outputs',
  'data',
  'text',
  'plain',
  'array',
  'execution_count',
  'metadata',
  'output_type',
  'execute_result',
  'source',
  'bow',
  'toarray',
  'cell_type',
  'code',
  'execution_count',
  'id',
  'dbda',
  'metadata',
  'outputs',
  'name',
  'stdout',
  'output_type',
  'stream',
  'text',
  'people',
  'watch',
  'dswithbappy',
  'dswithbappy',
  'watch',
  'dswithbappy',
  'people',
  'write',
  'comment',
  'dswithbappy',
  'write',
  'comment',
  'source',
  'print',
  'cv',
  'vocabulary_',
  'cell_type',
  'markdown',
  'id',
  'metadata',
  'source',
  'tf',
  'idf',
  'term',
  'frequency',
  'inverse',
  'document',
  'frequency',
  'cell_type',
  'code',
  'execution_count',
  'id',
  'metadata',
  'outputs',
  'data',
  'text',
  'html',
  'div',
  'style',
  'scoped',

In [27]:
model = gensim.models.Word2Vec(
    window=10,
    min_count=2
)

In [28]:
model.build_vocab(story)

In [29]:
model.train(story, total_examples=model.corpus_count, epochs=model.epochs)

(232452, 328875)

In [30]:
vec = model.wv.get_normed_vectors()

In [31]:
vec

array([[ 0.02517939,  0.10539257, -0.01789836, ..., -0.25972202,
         0.02362148, -0.03879691],
       [ 0.0198248 ,  0.10579091, -0.0211808 , ..., -0.25914615,
         0.03031425, -0.04337778],
       [ 0.0210031 ,  0.11112093, -0.02475179, ..., -0.2584012 ,
         0.03695344, -0.0495365 ],
       ...,
       [-0.02532568,  0.10550658, -0.03180919, ..., -0.2131351 ,
         0.10557029, -0.04641702],
       [ 0.00483298,  0.10203088, -0.03174058, ..., -0.2283772 ,
         0.11749382, -0.06444091],
       [-0.17748323, -0.07884622,  0.00881228, ...,  0.07569203,
         0.20803781, -0.03102046]], shape=(3669, 100), dtype=float32)

In [32]:
len(vec[0])

100

In [33]:
model.wv.most_similar('daenerys')

[('np', 0.9975531697273254),
 ('frequency', 0.9970065355300903),
 ('matrix', 0.9968634247779846),
 ('encoder', 0.9968123435974121),
 ('px', 0.9966465830802917),
 ('onehotencoder', 0.9966080784797668),
 ('punkt', 0.9965629577636719),
 ('ea', 0.9965021014213562),
 ('name', 0.9962647557258606),
 ('docs', 0.9960742592811584)]

In [34]:
model.wv.similarity('arya','sansa')

np.float32(0.9989502)

In [35]:
model.wv.index_to_key

['the',
 'and',
 'to',
 'he',
 'of',
 'his',
 'her',
 'was',
 'you',
 'it',
 'in',
 'she',
 'that',
 'had',
 'him',
 'as',
 'with',
 'said',
 'at',
 'for',
 'not',
 'on',
 'is',
 'but',
 'from',
 'they',
 'my',
 'arya',
 'be',
 'sansa',
 'have',
 'your',
 'no',
 'all',
 'lord',
 'would',
 'so',
 'were',
 'them',
 'me',
 'when',
 'bran',
 'there',
 'ned',
 'are',
 'could',
 'ser',
 'what',
 'king',
 'metadata',
 'up',
 'will',
 'out',
 'now',
 'jon',
 'like',
 'this',
 'execution_count',
 'man',
 'if',
 'one',
 'eyes',
 'we',
 'lady',
 'back',
 'hand',
 'been',
 'do',
 'looked',
 'boy',
 'text',
 'source',
 'cell_type',
 'an',
 'only',
 'down',
 'their',
 'id',
 'see',
 'page',
 'th',
 'outputs',
 'code',
 'then',
 'here',
 'joffrey',
 'did',
 'td',
 'can',
 'or',
 'know',
 'even',
 'told',
 'before',
 'old',
 'men',
 'than',
 'dswithbappy',
 'tyrion',
 'father',
 'by',
 'face',
 'white',
 'who',
 'never',
 'watch',
 'off',
 'where',
 'into',
 'away',
 'too',
 'lannister',
 'time',
 'over',
 'voice',
 'black',
 'tr',
 'way',
 'stark',
 'thought',
 'sword',
 'brother',
 'its',
 'still',
 'day',
 'long',
 'around',
 'saw',
 'queen',
 'us',
 'prince',
 'people',
 'maester',
 'littlefinger',
 'more',
 'look',
 'took',
 'catelyn',
 'through',
 'robert',
 'night',
 'go',
 'words',
 'came',
 'don',
 'll',
 'come',
 'am',
 'well',
 'knew',
 'dany',
 'asked',
 'null',
 'how',
 'great',
 'robb',
 'name',
 'little',
 'about',
 'two',
 'wall',
 'door',
 'heard',
 'years',
 'head',
 'after',
 'made',
 'just',
 'good',
 'again',
 'why',
 'write',
 'felt',
 'say',
 'stood',
 'tell',
 'some',
 'other',
 'found',
 'yet',
 'let',
 'table',
 'comment',
 'went',
 'sister',
 'left',
 'fingers',
 'word',
 'crow',
 'snow',
 'nothing',
 'wolf',
 'ever',
 'hard',
 'seemed',
 'across',
 'own',
 'has',
 'must',
 'himself',
 'our',
 'hands',
 'while',
 'winterfell',
 'called',
 'hair',
 'alone',
 'rodrik',
 'output_type',
 'once',
 'turned',
 'room',
 'arms',
 'until',
 'want',
 'tower',
 'first',
 'much',
 'beside',
 'far',
 'three',
 'girl',
 're',
 'moment',
 'green',
 'import',
 'north',
 'blood',
 'almost',
 'grey',
 'right',
 'data',
 'small',
 'high',
 'behind',
 'half',
 'make',
 'gave',
 'put',
 'summer',
 'hear',
 'nymeria',
 'always',
 'find',
 'castle',
 'gone',
 'perhaps',
 'direwolf',
 'another',
 'think',
 'done',
 'alliser',
 'take',
 'true',
 'ride',
 'should',
 'plain',
 'red',
 'cold',
 'mother',
 'against',
 'last',
 'though',
 'seen',
 'septa',
 'leave',
 'mormont',
 'dead',
 'end',
 'things',
 'jory',
 'silver',
 'child',
 'both',
 'mycah',
 'might',
 'woman',
 'between',
 'type',
 'son',
 'beneath',
 'began',
 'fear',
 'steel',
 'enough',
 'dataframe',
 'varys',
 'any',
 'seat',
 'below',
 'most',
 'feet',
 'fell',
 'sun',
 'knight',
 'wanted',
 'place',
 'horse',
 'side',
 'water',
 'get',
 'lost',
 'under',
 'shall',
 'need',
 'arm',
 'execute_result',
 'ticks',
 'past',
 'renly',
 'butcher',
 'dark',
 'pale',
 'herself',
 'may',
 'thing',
 'every',
 'feel',
 'keep',
 'replied',
 'blue',
 'ground',
 'hall',
 'lifted',
 'thick',
 'commander',
 'sweet',
 'smile',
 'afraid',
 'seven',
 'laughed',
 'air',
 'going',
 'looking',
 'eddard',
 'sea',
 'bed',
 'stone',
 'sent',
 'story',
 'hodor',
 'others',
 'river',
 'pulled',
 'sat',
 'better',
 'honor',
 'mordane',
 'gods',
 'dagger',
 'very',
 'brothers',
 'smiled',
 'tears',
 'help',
 'those',
 'stop',
 'these',
 'strong',
 'children',
 'luwin',
 'window',
 'align',
 'jorah',
 'rode',
 'wind',
 'young',
 'golden',
 'leather',
 'rest',
 'didn',
 'something',
 'does',
 'life',
 'model',
 'tbody',
 'pycelle',
 'yes',
 'reached',
 'heavy',
 'shoulder',
 'hundred',
 'best',
 've',
 'landing',
 'nltk',
 'city',
 'thorne',
 'nan',
 'dothraki',
 'world',
 'ice',
 'hit',
 'blade',
 'without',
 'love',
 'set',
 'hot',
 'viserys',
 'petyr',
 'falling',
 'legs',
 'truth',
 'heart',
 'tried',
 'hurt',
 'hound',
 'spoke',
 'above',
 'armor',
 'days',
 'won',
 'wooden',
 'ran',
 'few',
 'bring',
 'deep',
 'open',
 'bow',
 'moreo',
 'yard',
 'taken',
 'brought',
 'pain',
 'happened',
 'grass',
 'chest',
 'grew',
 'oh',
 'give',
 'together',
 'doing',
 'fire',
 'cloak',
 'steps',
 'talk',
 'along',
 'lion',
 'trident',
 'slid',
 'cv',
 'brandon',
 'thousand',
 'fall',
 'dragon',
 'soon',
 'wood',
 'uncle',
 'moved',
 'council',
 'friend',
 'riding',
 'believe',
 'mean',
 'send',
 'style',
 'df',
 'outlinewidth',
 'colorbar',
 'arryn',
 'shadow',
 'walls',
 'fly',
 'dragons',
 'died',
 'rose',
 'stick',
 'each',
 'finally',
 'laughter',
 'daughter',
 'kind',
 'breath',
 'four',
 'common',
 'inside',
 'ago',
 'morning',
 'coming',
 'thead',
 'output',
 'grenn',
 'stories',
 'grand',
 'winter',
 'remembered',
 'toward',
 'beyond',
 'woods',
 'barristan',
 'terrible',
 'anything',
 'whispered',
 'bastard',
 'care',
 'hold',
 'followed',
 'gold',
 'everything',
 'same',
 'opened',
 'darkness',
 'cry',
 'remember',
 'cersei',
 'tooth',
 'sorry',
 'mouth',
 'suddenly',
 'upon',
 'knights',
 'closer',
 'south',
 'close',
 'sometimes',
 'third',
 'outside',
 'dog',
 'fast',
 'many',
 'often',
 'rickon',
 'irri',
 'baelish',
 'agreed',
 'death',
 'throat',
 'scarcely',
 'screamed',
 'swung',
 'wine',
 'please',
 'speak',
 'grace',
 'ilyn',
 'drew',
 'swords',
 'since',
 'filled',
 'forest',
 'lie',
 'understand',
 'shouted',
 'watched',
 'girls',
 'sleep',
 'got',
 'covered',
 'trees',
 'narrow',
 'neck',
 'hate',
 'less',
 'tall',
 'already',
 'wheelhouse',
 'princess',
 'wild',
 'kingsroad',
 'array',
 'kingdoms',
 'dwarf',
 'benjen',
 'moon',
 'captain',
 'light',
 'promise',
 'promised',
 'poole',
 'soft',
 'bright',
 'cried',
 'call',
 'walked',
 'truly',
 'wrong',
 'older',
 'bowed',
 'iron',
 'guard',
 'someone',
 'forgotten',
 'walk',
 'such',
 'liked',
 'watching',
 'waiting',
 'flowers',
 'horses',
 'nodded',
 'lannisters',
 'vec',
 'show',
 'names',
 'print',
 'fit_transform',
 'color',
 'needle',
 'pray',
 'galley',
 'sky',
 'cut',
 'wife',
 'bear',
 'seem',
 'flew',
 'body',
 'holding',
 'frozen',
 'sound',
 'warm',
 'safe',
 'targaryen',
 'near',
 'saying',
 'real',
 'different',
 'free',
 'whole',
 'run',
 'kept',
 'killed',
 'fur',
 'brushed',
 'royal',
 'myrcella',
 'today',
 'broke',
 'ahead',
 'knife',
 'running',
 'top',
 'fat',
 'home',
 'khalasar',
 'sudden',
 'forget',
 'die',
 'beard',
 'steward',
 'stay',
 'listen',
 'east',
 'fight',
 'touch',
 'realm',
 'skin',
 'baratheon',
 'anger',
 'fool',
 'burned',
 'grown',
 'helm',
 'smiling',
 'starks',
 'born',
 'master',
 'shoulders',
 'worse',
 'stopped',
 'none',
 'shrugged',
 'full',
 'myself',
 'python',
 'tokens',
 'wv',
 'read',
 'given',
 'vertical',
 'div',
 'marker',
 'known',
 'ghost',
 'yoren',
 'doubt',
 'khaleesi',
 'drogo',
 'short',
 'longer',
 'live',
 'shore',
 'cities',
 'oars',
 'earth',
 'maybe',
 'wings',
 'started',
 'vast',
 'part',
 'yours',
 'business',
 'damn',
 'thank',
 'broken',
 'blow',
 'line',
 'eye',
 'year',
 'grip',
 'ask',
 'being',
 'quite',
 'answer',
 'shining',
 'wet',
 'laid',
 'cheeks',
 'twenty',
 'new',
 'wore',
 'aside',
 'voices',
 'quickly',
 'quietly',
 'spun',
 'teeth',
 'snapped',
 'stupid',
 'which',
 'forward',
 'picked',
 'hungry',
 'wasn',
 'tongue',
 'winds',
 'faster',
 'yourself',
 'stream',
 'linecolor',
 'gridcolor',
 'carried',
 'hope',
 'edge',
 'empty',
 'noye',
 'wonder',
 'held',
 'tyroshi',
 'bird',
 'cannot',
 'burst',
 'lived',
 'closed',
 'flesh',
 'pick',
 'jaime',
 'slow',
 'glanced',
 'led',
 'gently',
 'realized',
 'else',
 'dropped',
 'shaking',
 'stepped',
 'slowly',
 'silence',
 'kingsguard',
 'ignored',
 'meat',
 'caught',
 'next',
 'huge',
 'pressed',
 'hated',
 'pointed',
 'lands',
 'poor',
 'struggled',
 'return',
 'fb',
 'vocabulary',
 'stdout',
 'pd',
 'al',
 'learn',
 'try',
 'cruel',
 'command',
 'wait',
 'seated',
 'certain',
 'armory',
 'tourney',
 'toad',
 'wolves',
 'jhiqui',
 'built',
 'afterward',
 'become',
 'heat',
 'spread',
 'landed',
 'dressed',
 'says',
 'later',
 'rising',
 'liar',
 'insisted',
 'floor',
 'loudly',
 'matter',
 'raymun',
 'whip',
 'seems',
 'aemon',
 'aerys',
 'hells',
 'muttered',
 'backward',
 'use',
 'lords',
 'meant',
 'eat',
 'ears',
 'slept',
 'serving',
 'clothes',
 'endless',
 'sore',
 'rhaegar',
 'rubies',
 'brush',
 'trying',
 'inn',
 'heels',
 'bench',
 'hours',
 'noble',
 'follow',
 'least',
 'party',
 'escort',
 'stopwords',
 'download',
 'used',
 'toarray',
 'shape',
 'countvectorizer',
 'middle',
 'markdown',
 'commanded',
 'needs',
 'knows',
 'tired',
 'question',
 'spent',
 'armorer',
 'kill',
 'among',
 'sit',
 'higher',
 'dance',
 'tent',
 'whiskers',
 'loved',
 'big',
 'touched',
 'fled',
 'warmth',
 'chill',
 'corn',
 'front',
 'walking',
 'husband',
 'lead',
 'flat',
 'bite',
 'raised',
 'talking',
 'turn',
 'darry',
 'themselves',
 'vayon',
 'lay',
 'flying',
 'eyed',
 'stronger',
 'cup',
 'longsword',
 'following',
 'pleasure',
 'silent',
 'waited',
 'low',
 'beautiful',
 'frighten',
 'twisted',
 'clean',
 'hung',
 'sisters',
 'grabbed',
 'baby',
 'leg',
 'because',
 'crown',
 'mud',
 'household',
 'really',
 'thinking',
 'onto',
 'aurochs',
 'ship',
 'taking',
 'theon',
 'friends',
 'ae',
 'np',
 'ecf',
 'ak',
 'dozen',
 'late',
 'cat',
 'gestured',
 'birds',
 'rather',
 'wrist',
 'boys',
 'pyp',
 'halder',
 'mind',
 'septon',
 'curious',
 'fighting',
 'times',
 'servants',
 'message',
 'raven',
 'chambers',
 'chair',
 'sighed',
 'softly',
 'greyjoy',
 'milk',
 'cage',
 'tom',
 'grasses',
 'hill',
 'aegon',
 'hills',
 'letter',
 'announced',
 'court',
 'somehow',
 'rail',
 'stared',
 'stables',
 'dream',
 'woke',
 'mists',
 'teach',
 'ones',
 'boots',
 'nor',
 'crossed',
 'needed',
 'blind',
 'sharply',
 'wide',
 'sleeve',
 'storm',
 'wool',
 'clegane',
 'sandor',
 'weight',
 'stranger',
 'laughing',
 'plate',
 'whose',
 'fine',
 'doors',
 'apart',
 'whirled',
 'threw',
 'haunted',
 'supposed',
 'purple',
 'camp',
 'windows',
 'road',
 'strange',
 'betrothed',
 'shone',
 'velvet',
 'harbor',
 'wagons',
 'move',
 'riders',
 'version',
 'plotly',
 'pca',
 'ab',
 'corpus',
 'vocabulary_',
 'bag',
 'sklearn',
 'ed',
 'bo',
 'ju',
 ...]

In [36]:
from sklearn.decomposition import PCA

In [37]:
pca = PCA(n_components=3)

In [38]:
X = pca.fit_transform(model.wv.get_normed_vectors())

In [39]:
X

array([[ 0.00157362, -0.20109598, -0.0517993 ],
       [ 0.00803417, -0.15954104, -0.05415396],
       [ 0.00280029, -0.18014252, -0.07370465],
       ...,
       [-0.0144735 ,  0.21577378,  0.00149457],
       [-0.02875769,  0.25501847, -0.02395348],
       [-1.1897802 ,  0.8487223 , -0.15953891]],
      shape=(3669, 3), dtype=float32)

In [40]:
X

array([[ 0.00157362, -0.20109598, -0.0517993 ],
       [ 0.00803417, -0.15954104, -0.05415396],
       [ 0.00280029, -0.18014252, -0.07370465],
       ...,
       [-0.0144735 ,  0.21577378,  0.00149457],
       [-0.02875769,  0.25501847, -0.02395348],
       [-1.1897802 ,  0.8487223 , -0.15953891]],
      shape=(3669, 3), dtype=float32)

In [41]:
! pip install plotly

Requirement already satisfied: plotly in /Users/al-amen/Documents/Generative AI/venv/lib/python3.12/site-packages (6.5.2)
Requirement already satisfied: narwhals>=1.15.1 in /Users/al-amen/Documents/Generative AI/venv/lib/python3.12/site-packages (from plotly) (2.16.0)
Requirement already satisfied: packaging in /Users/al-amen/Documents/Generative AI/venv/lib/python3.12/site-packages (from plotly) (26.0)

In [42]:
import plotly.express as px
fig = px.scatter_3d(x=X[:,0], y=X[:,1], z=X[:,2], text=model.wv.index_to_key)
fig.show()

In [43]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize
import string

# Download NLTK resource
nltk.download('punkt')
nltk.download('stopwords')

# Sample text (can be read from a file too)

[nltk_data] Downloading package punkt to /Users/al-amen/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /Users/al-
[nltk_data]     amen/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [44]:
docs = [
    "John is working on Natural Language Processing.",
    "He was running and eating at the same time.",
    "His friends were working on deep learning models."
]

In [45]:
# Preprocessing function

def preprocess(text):
    # Lower case
    text = text.lower()
    # Tokenize
    tokens = word_tokenize(text)
    # Remove punctuation and stopwords
    stop_words = set(stopwords.words('english'))
    tokens = [word for word in tokens if word not in stop_words and word not in string.punctuation]
    # stemming 
    stemmer = PorterStemmer()
    tokens = [stemmer.stem(word) for word in tokens]
    return ' '.join(tokens)

# Preprocess the documents
cleaned_docs = [preprocess(doc) for doc in docs]

cleaned_docs

['john work natur languag process',
 'run eat time',
 'friend work deep learn model']

In [46]:
# Create Bag of words
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(cleaned_docs)

In [47]:
# Show vocabulary
print("Vocabulary:", vectorizer.vocabulary_)

Vocabulary: {'john': 3, 'work': 11, 'natur': 7, 'languag': 4, 'process': 8, 'run': 9, 'eat': 1, 'time': 10, 'friend': 2, 'deep': 0, 'learn': 5, 'model': 6}

In [48]:
# Show Bow matrix
print("\nBag of Words Matrix:\n", X.toarray())

Bag of Words Matrix:
 [[0 0 0 1 1 0 0 1 1 0 0 1]
 [0 1 0 0 0 0 0 0 0 1 1 0]
 [1 0 1 0 0 1 1 0 0 0 0 1]]